name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::163161484468:user/marcelonakata
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change this to your desired AWS region

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Build Environment
        env:
          ECR_REPOSITORY_URI: 163161484468.dkr.ecr.us-east-1.amazonaws.com/test_repo  # Replace with your ECR repository URI
        run: echo "ECR_REPOSITORY_URI=$ECR_REPOSITORY_URI" >> $GITHUB_ENV
    
      - name: Build and run Docker image
        run: |
          docker build -t $ECR_REPOSITORY_URI .
          docker push $ECR_REPOSITORY_URI
          docker run -v ${PWD}/playwright-report:/app/playwright-report/ $ECR_REPOSITORY_URI
    
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
        